### ISSUE TITLE
command.com (without /P) should return %ERRORLEVEL% rather than zero

### ISSUE THREAD

**Issue by dgorski** [FDOS/freecom#22]
Hi, I noticed main() returns zero rather that the current errorlevel.  This makes freecom unusable as a sub-shell for executables (like BBS systems) that are capable of running batch files while they are still resident.  It seems like a pretty simple fix to the last line(s) of `shell/command.c`

Current always returns zero (why?)
```
  return 0;
}
```
Simple change returns the last command's ERRORLEVEL:
```

  return errorlevel;
}
```

**Comment by dgorski** [comment]
Added #26 with this fix.

**Comment by stuaxo** [comment]
LGTM @francescosacco can this be merged ?

**Comment by stuaxo** [comment]
Who is the best person to merge this, @PerditionC ?

**Comment by PerditionC** [comment]
Yes, PR was merged

**Comment by stuaxo** [comment]
Thanks :)

**Comment by dgorski** [comment]
FWIW - I've been running a build with this patch since I created the merge request with zero stability issues.

**Comment by dgorski** [comment]
I realized the other day that I had promised to re-test and close but I never did.  So I pulled the latest and built with WATCOM under FreeDOS 1.3.  FreeCOM now properly exits with %errorlevel% as expected.

![image](https://user-images.githubusercontent.com/2665156/101871313-5a66ac00-3b51-11eb-9c7b-be4c6baf8fb8.png)

**Comment by stuaxo** [comment]
@andrewbird not sure if this affects your DOS tests ?

**Comment by andrewbird** [comment]
Thanks for the heads-up! Fortunately it won't bother me because I write the DOS part of the tests to return text strings and in the python part I use unittest's `assert*()` to test that text output. I find preferable to write the pass/fail logic in python based on text screen output, any content created, host file system changes, or Dosemu logs / errors. The downside is that it doesn't really make a very useful standalone DOS test.

I should probably add a test to Dosemu that the return value is propagated all the way out to the Unix shell, though.
