### ISSUE TITLE
Internal commands don't set ERRORLEVEL

### ISSUE THREAD

**Issue by francescosacco** [FDOS/freecom#28]
Internal commands should set the ERRORLEVEL, just like normal commands. However, it doesn't happen as we can see below.

![image](https://user-images.githubusercontent.com/18581159/92433717-425b4700-f174-11ea-9c59-5257efeb0316.png)

**Comment by andrewbird** [comment]
@PerditionC presumably this can be closed now?

**Comment by PerditionC** [comment]
Yes, I left it open because I wanted to see if a similar fix was still needed for comcom

**Comment by andrewbird** [comment]
I don't have much recent experience with DOS batchfiles so the example below may be flawed, but I just tested with Dosemu2 and MS-DOS 6.22 and it seems that it doesn't report the success/fail of internal commands. With an external command the success / fail worked as expected.

~~~
@echo off

rem External command that succeeds
rem ISEMU

rem External command that fails (due to configuration)
rem FOSSIL

rem Internal command (X: doesn't exist)
DIR X:

if ERRORLEVEL 1 goto error

:isokay
echo okay
goto done

:error
echo with error

:done
~~~

~~~
C:\>mytest
Invalid drive specification
okay
~~~

**Comment by dgorski** [comment]
Related to #22 - exit always returns zero from a subshell, but exiting a batch file (as long as it doesn't end with exit) returns the errorlevel.  This is specific to a non-permanent shell (subshell).  

exit should return the errorlevel to the calling shell.

'exit' probably shouldn't do anything at all for a /P shell (including alter the errorlevel).

```
C:\>ver /r

FreeCom version 0.85a - WATCOMC - XMS_Swap [Jul 10 2021 19:28:06]
DOS version 7.10
FreeDOS kernel 2043 (build 2043 OEM:0xfd) [compiled May 14 2021]
C:\>type test.bat
@echo test.bat
@c:\utils\err 2
@if "%1"=="exit" exit

C:\>command /c test.bat
test.bat
C:\>echo %errorlevel%
2
C:\>command /c test.bat exit
test.bat
C:\>echo %errorlevel%
0
C:\>

```
