### ISSUE TITLE
How to build? (Linux crosscompiling with ia16 gcc)

### ISSUE THREAD

**Issue by ecm-pushbx** [FDOS/freecom#59]
I just tried building FreeCOM with a very recent (last week's) ia16 gcc, using the command `./build.sh gcc`. What appears to be the final linking of `command.exe` fails with lots of undefined references to Unix style functions with prepended underscore. This is the command:

```
ia16-elf-gcc -mcmodel=small -Os -Wall -Werror -Wno-pointer-to-int-cast -Wno-incompatible-pointer-types -mregparmcall -fno-builtin -fno-strict-aliasing -Wno-format -mfar-function-if-far-return-type -fno-caller-saves -fno-optimize-sibling-calls -fno-move-loop-invariants -fno-tree-loop-optimize -fno-rerun-cse-after-loop -o command.exe  cb_catch.obj termhook.obj xms_crit.obj xms_brk.obj xms_2e.obj cswap.obj cswapc.obj batch.obj cmdtable.obj command.obj expalias.obj init.obj kswap.obj loadhigh.obj module.obj redir.obj ver.obj command.ld ../cmd/cmds.lib ../lib/freecom.lib ../strings/strings.lib ../suppl/suppl_s.lib  -Wl,-Map,command.map # @command.rsp
```

And this is a short excerpt of the resulting errors:

```
[homedir]/proj/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/bin/ld: batch.obj: in function `clearBatchContext':
(.text+0xa): undefined reference to `_close'
[homedir]/proj/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/bin/ld: batch.obj: in function `readbatchline':
(.text+0x2f2): undefined reference to `_close'
[homedir]/proj/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/bin/ld: (.text+0x392): undefined reference to `_open'
[homedir]/proj/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/bin/ld: (.text+0x3d2): undefined reference to `_lseek'
[homedir]/proj/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/bin/ld: (.text+0x450): undefined reference to `_lseek'
[homedir]/proj/build-ia16/prefix/lib/gcc/ia16-elf/6.3.0/../../../../ia16-elf/bin/ld: command.obj: in function `parsecommandline':
(.text+0x496): undefined reference to `_close'
```

Full log file [is uploaded here](https://pushbx.org/ecm/test/20211102.log).

**Comment by tkchia** [comment]
Hello @ecm-pushbx, hello @PerditionC,

This is a bug in FreeCOM.

The problem is that `newlib-ia16` 's `_open`, `_lseek`, and `_close` functions were internal functions &mdash; these were used to implement the "reentrant" `_open_r` etc. functions which in turn implement `open` etc.  And FreeCOM was incorrectly using these internal functions.  (Last month &mdash; https://github.com/tkchia/newlib-ia16/commit/da89591ff6069bf21a473aafa4a81c31292d3496 &mdash; I modified the `newlib-ia16` internals, to implement `_open_r` etc. directly.)

What you probably want is to either
  * use the `_dos_open` and `_dos_close` functions from my [`libi86` library](https://github.com/tkchia/libi86), or
  * implement these directly in `lib/farread.c`.

For `lseek`, just use the real `lseek` function.

`libi86` 's `_dos_open` and `_dos_close` functions are meant to have the same meanings as in Watcom &mdash; i.e. they map directly to the MS-DOS functions `0x3d` and `0x3e`.

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx, hello @PerditionC,

I have submitted a quick fix (https://github.com/FDOS/freecom/pull/60) to tackle this problem.

The proposed fix simply implements `sfn_open` and `dos_close` directly in `lib/farread.c` (and does not need my `libi86`).

Thank you!

**Comment by ecm-pushbx** [comment]
Just did a `git pull` then had to `./build.sh clean` and now `./build.sh gcc` works as expected!
